name: Build and Deploy Hugo to GCP

on: push

jobs:
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://jojomi/hugo
      env:
        HUGO_ENV: production
        HUGO_DESTINATION: /github/workspace/public
    - run: ls -al public
